<?php  //[STAMP] d48113fecb546d4db2429257def19c65
namespace choateunit\yii\captcha\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use choateunit\yii\captcha\Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
